### ISSUE TITLE
" glitch

### ISSUE THREAD

**Issue by koala4987** [Toemmsen96/ChatCommands#18]
whenever i try to run a command, it just types " in chat and does nothing.

**Comment by Toemmsen96** [comment]
The " in chat is normal, yes it is a bug. However it should still do stuff. The problem is probably the updates this game has gotten. I have not played it and not programmed for it in quite a while. Im not sure if i will update this anytime soon, but i will look into it if its a quick fix.

**Comment by Toemmsen96** [comment]
for me everything seems normal, i pushed an update, maybe sth fixes this for you

**Comment by Toemmsen96** [comment]
is this in a online game as non host or are you host?

**Comment by koala4987** [comment]
it sometimes happens when i am host but it always happens when i am non host

**Comment by koala4987** [comment]
i just tested and it doesn't work

**Comment by Toemmsen96** [comment]
> i just tested and it doesn't work

very well possible that it is an issue with other mods if you have any installed. maybe test if it works if only this one is enabled.
still please tell me what exactly the lobby is you are in, are you host?, are you playing with friends?. Please provide a screen shot of the BepInEx console.
otherwise i cant help.

**Comment by koala4987** [comment]
ok i will try with nothing else

**Comment by koala4987** [comment]
thanks for the help it works
